# Malnati/pr-comment@v5.0.0
name: "PR Comment Template"
description: "Post standard, templated comments on Pull Requests (header/body/footer)."
author: "Ricardo Malnati"

branding:
  icon: "message-circle"
  color: "purple"

inputs:
  token:
    description: "GitHub token (e.g., secrets.GITHUB_TOKEN)"
    required: true
  pr_number:
    description: "Pull Request number to comment on"
    required: true
  header_actor:
    description: "Message author"
    required: true
  header_title:
    description: "Comment title"
    required: true
  header_subject:
    description: "Comment subject"
    required: true
  body_message:
    description: "Main message body (Markdown)"
    required: true
  body_scope:
    description: "Scope text (Raw)"
    required: false
    default: ""
  body_todo:
    description: "TODO text (Raw)"
    required: false
    default: ""
  footer_result:
    description: "Result summary (Raw)"
    required: false
    default: ""
  footer_advise:
    description: "Advice / next steps (Raw)"
    required: false
    default: ""
  template_path:
    description: "Path to custom Markdown template"
    required: false
    default: ""
    
outputs:
  comment_body:
    description: "Final comment body"
    value: ${{ steps.assemble_markdown.outputs.markdown }}

runs:
  using: "composite"
  steps:
    # ------------------------------------------------------------------
    # STEP 1, 2 e 3: Pass-through (Sem alterações, mantém a limpeza)
    # ------------------------------------------------------------------
    - id: fmt_scope
      shell: bash
      env:
        RAW_SCOPE: ${{ inputs.body_scope }}
      run: |
        echo "block<<EOF"
        echo "$RAW_SCOPE"
        echo "EOF" >> "$GITHUB_OUTPUT"

    - id: fmt_todo
      shell: bash
      env:
        RAW_TODO: ${{ inputs.body_todo }}
      run: |
        echo "block<<EOF"
        echo "$RAW_TODO"
        echo "EOF" >> "$GITHUB_OUTPUT"

    - id: fmt_footer
      shell: bash
      env:
        RES: ${{ inputs.footer_result }}
        ADV: ${{ inputs.footer_advise }}
      run: |
        FORMATTED=""
        if [ -n "$RES" ]; then
           FORMATTED="$RES"
        fi
        if [ -n "$ADV" ]; then
           if [ -n "$FORMATTED" ]; then
              FORMATTED="${FORMATTED}<br>${ADV}"
           else
              FORMATTED="$ADV"
           fi
        fi
        echo "block<<EOF"
        echo "$FORMATTED"
        echo "EOF" >> "$GITHUB_OUTPUT"

    # ------------------------------------------------------------------
    # STEP 3.5: Validar Template (LOGS APENAS)
    # Mudança: Usamos ::warning:: em vez de injetar texto no output.
    # ------------------------------------------------------------------
    - id: check_template
      shell: bash
      env:
        CUSTOM_PATH: ${{ inputs.template_path }}
        DEFAULT_PATH: ${{ github.action_path }}/templates/pr-comment.md
      run: |
        set -euo pipefail

        REQUIRED_VARS=("BODY_MESSAGE")
        FINAL_TEMPLATE="$DEFAULT_PATH"

        # 1. Sem template customizado -> Usa Default (Normal)
        if [ -z "$CUSTOM_PATH" ]; then
          echo "Using default template."
        
        # 2. Template não existe -> Aviso no Log + Fallback
        elif [ ! -f "$CUSTOM_PATH" ]; then
          echo "::warning title=Template Not Found::O arquivo '$CUSTOM_PATH' não foi encontrado. Usando template padrão."
          FINAL_TEMPLATE="$DEFAULT_PATH"

        # 3. Validação de placeholders -> Aviso no Log + Fallback
        else
          MISSING=()
          for VAR in "${REQUIRED_VARS[@]}"; do
            if ! grep -Fq "\${$VAR}" "$CUSTOM_PATH" && ! grep -Fq "\$$VAR" "$CUSTOM_PATH"; then
               MISSING+=("$VAR")
            fi
          done

          if [ ${#MISSING[@]} -gt 0 ]; then
            MISSING_STR=$(IFS=', '; echo "${MISSING[*]}")
            echo "::warning title=Invalid Template::O template personalizado falhou na validação. Faltam: [$MISSING_STR]. Usando padrão."
            FINAL_TEMPLATE="$DEFAULT_PATH"
          else
            echo "Template validado com sucesso."
            FINAL_TEMPLATE="$CUSTOM_PATH"
          fi
        fi

        echo "template_file=$FINAL_TEMPLATE" >> "$GITHUB_OUTPUT"

    # ------------------------------------------------------------------
    # STEP 4: Montar Markdown Final
    # Mudança: Removemos a lógica de WARNING_APPEND.
    # ------------------------------------------------------------------
    - id: assemble_markdown
      shell: bash
      env:
        ACTOR: ${{ inputs.header_actor }}
        TITLE: ${{ inputs.header_title }}
        SUBJECT: ${{ inputs.header_subject }}
        BODY_MESSAGE: ${{ inputs.body_message }}
        RAW_SCOPE: ${{ steps.fmt_scope.outputs.block }}
        RAW_TODO: ${{ steps.fmt_todo.outputs.block }}
        RAW_FOOTER: ${{ steps.fmt_footer.outputs.block }}
        TEMPLATE_PATH: ${{ steps.check_template.outputs.template_file }}
      run: |
        set -euo pipefail

        if [ ! -f "$TEMPLATE_PATH" ]; then
          echo "::error::Critical: Template path invalido."
          exit 1
        fi

        export ACTOR TITLE SUBJECT BODY_MESSAGE
        export BODY_SCOPE_BLOCK="$RAW_SCOPE"
        export BODY_TODO_BLOCK="$RAW_TODO"
        export FOOTER_BLOCK="$RAW_FOOTER"

        # Apenas substitui e salva. Se houve erro de template,
        # o usuário verá nos logs da Action, não no texto da PR.
        MARKDOWN_CONTENT=$(envsubst < "$TEMPLATE_PATH")

        echo "markdown<<EOF"
        echo "$MARKDOWN_CONTENT"
        echo "EOF" >> "$GITHUB_OUTPUT"
        
    # ------------------------------------------------------------------
    # STEP 5: Preparar JSON
    # ------------------------------------------------------------------
    - id: prepare_json
      shell: bash
      env:
        CONTENT: ${{ steps.assemble_markdown.outputs.markdown }}
      run: |
        set -euo pipefail
        JSON_PAYLOAD=$(printf '%s' "$CONTENT" | jq -Rs '{body: .}')

        echo "payload<<EOF"
        echo "$JSON_PAYLOAD"
        echo "EOF" >> "$GITHUB_OUTPUT"

    # ------------------------------------------------------------------
    # STEP 6: Request
    # ------------------------------------------------------------------
    - id: post_comment
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        REPO: ${{ github.repository }}
        PR_NUM: ${{ inputs.pr_number }}
        JSON_DATA: ${{ steps.prepare_json.outputs.payload }}
      run: |
        set -euo pipefail
        URL="https://api.github.com/repos/$REPO/issues/$PR_NUM/comments"
        
        HTTP_CODE=$(curl -sS -w "%{http_code}" -o response.json \
          -H "Authorization: Bearer $TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -X POST "$URL" \
          -d "$JSON_DATA")

        if [[ "$HTTP_CODE" -lt 200 || "$HTTP_CODE" -ge 300 ]]; then
          echo "::error::Failed to post comment. HTTP Code: $HTTP_CODE"
          cat response.json
          exit 1
        else
          echo "Comment posted successfully."
        fi
